### ISSUE TITLE
Investigate EA plugin infrastructure

### ISSUE THREAD

**Issue by alexatrhea** [RHEAGROUP/DEH-EASYSML#1]
- [x] Install EA and investigate the mechanism to create plugins.
- [x] Verify working of DEH-COMMON within the project
- [x] Create and setup solution on `development` branch

**Comment by nathanatrhea** [comment]
https://sparxsystems.com/enterprise_architect_user_guide/15.2/model_repository/pcs_integration_plugins_custom_write.html
